---

- hosts: database
  become: true
  tasks:

  - name: Create groups for the admins, doctors and interns
    ansible.builtin.group:
      name: "{{ item.name }}"
      state: present
    loop:
      - { name: 'admin' }
      - { name: 'staff' }
      - { name: 'intern' }

  - name: Create users and set their groups and potential home directories
    user:
      name: "{{ item.user }}"
      groups: "{{ item.group }}"
      create_home: "{{ item.create_home }}"
      append: yes
    loop:
      - { user: 'armin', group: 'admin', create_home: 'yes' }
      - { user: 'edgar', group: 'staff', create_home: 'no' }
      - { user: 'tina', group: 'intern', create_home: 'no' }
